openapi: 3.0.0
info:
  title: Exemplo de API de Produtos
  version: 1.0.0
paths:
  /produtos:
    summary: Operações sobre produtos
    get:
      tags:
        - produtos
      summary: Lista de Produtos
      description: Retorna a lista de produtos disponíveis.
      operationId: getProdutos
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
              examples:
                produtos_json:
                  value:
                  - id: 1
                    nome: Produto A
                    preco: 19.99
                  - id: 2
                    nome: Produto B
                    preco: 24.99
        404:
          description: Não encontrado
  /produtos/{id}:
    summary: Localiza o produto pelo identificador
    get:
      operationId: getProdutoById
      parameters:
        - examples:
            1:
              value: 1
            2:
              value: 2
          name: id
          description: identificador do produto
          schema:
            type: integer
          in: path
          required: true
      responses:
        200:
          description: Sucesso ao buscar produto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
              examples:
                1:
                  value:
                    id: 1
                    nome: Produto A
                    preco: 19.99
                2:
                  value:
                    id: 2
                    nome: Produto B
                    preco: 24.99
components:
  schemas:
    Produto:
      properties:
        id:
          description: Identificador do produto
          type: integer
        nome:
          description: Nome do produto
          type: string
        preco:
          description: Valor de venda do produto
          type: number
          format: double
      example:
        id: 1
        nome: Cadeira flexform
        preco: 100.00
